### ISSUE TITLE
FrameworkEvent ERROR

### ISSUE THREAD

**Issue by nokia001** [scurb/NeatoBinding#3]
Unresolved requirement: Import-Package: org.openhab.core.library.types

What is here wrong?

**Comment by nokia001** [comment]
Ok. Newer Version of OH2 (https://bintray.com/openhab/mvn/download_file?file_path=org%2Fopenhab%2Fdistro%2Fopenhab%2F2.2.0%2Fopenhab-2.2.0.zip)

Same problem:
2017-12-19 18:07:48.661 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/opt/openhab2_2/addons/org.openhab.binding.neato_2.0.0.201702202022.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.neato [196]
  Unresolved requirement: Import-Package: org.apache.commons.codec.binary; version="1.6.0"

        at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) [?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312) [8:org.apache.felix.fileinstall:3.5.8]
2017-12-19 18:10:59.924 [INFO ] [.internal.GenericScriptEngineFactory] - Activated scripting support for ECMAScript
2017-12-19 18:11:08.675 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/opt/openhab2_2/addons/org.openhab.binding.neato_2.0.0.201702202022.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.neato [196]
  Unresolved requirement: Import-Package: org.apache.commons.codec.binary; version="1.6.0"

        at org.eclipse.osgi.container.Module.start(Module.java:444) [?:?]
        at org.eclipse.osgi.internal.framework.EquinoxBundle.start(EquinoxBundle.java:383) [?:?]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundle(DirectoryWatcher.java:1253) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.startBundles(DirectoryWatcher.java:1225) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.doProcess(DirectoryWatcher.java:512) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.process(DirectoryWatcher.java:361) [8:org.apache.felix.fileinstall:3.5.8]
        at org.apache.felix.fileinstall.internal.DirectoryWatcher.run(DirectoryWatcher.java:312) [8:org.apache.felix.fileinstall:3.5.8]
2017-12-19 18:11:28.680 [WARN ] [org.apache.felix.fileinstall        ] - Error while starting bundle: file:/opt/openhab2_2/addons/org.openhab.binding.neato_2.0.0.201702202022.jar
org.osgi.framework.BundleException: Could not resolve module: org.openhab.binding.neato [196]
  Unresolved requirement: Import-Package: org.openhab.core.library.types
